export function getTextClearedOfTags(text) {
   return text
      .replaceAll(/<[^>]*>/gi, "")
      .replace(/&nbsp;/g, " ")
      .replace(/&quot;|&#34;/g, '"')
      .replace(/&amp;|&#38;/g, "&")
      .replace(/&lt;|&#60;/g, "<")
      .replace(/&gt;|&#62;/g, ">")
      .replace(/&ndash;|&#8211;/g, "-")
      .replace(/&mdash;|&#8212;/g, "—")
      .replace(/&#769;/g, "́")
      .replace(/&acute;|&#180;/g, "´")
      .replace(/&prime;|&#8242;/g, "′")
      .replace(/&Prime;|&#8243;/g, "″")
      .replace(/&lsquo;|&#8216;/g, "‘")
      .replace(/&rsquo;|&#8217;/g, "’")
      .replace(/&sbquo;|&#8218;/g, "‚")
      .replace(/&ldquo;|&#8220;/g, "“")
      .replace(/&rdquo;|&#8221;/g, "”")
      .replace(/&bdquo;|&#8222;/g, "„")
      .replace(/&laquo;|&#171;/g, "«")
      .replace(/&raquo;|&#187;/g, "»")
      .replace(/&hellip;|&#8230;/g, "…")
      .replace(/&sect;|&#167;/g, "§")
      .replace(/&copy;|&#169;/g, "©")
      .replace(/&deg;|&#176;/g, "°")
      .replace(/&permil;|&#8240;/g, "‰")
      .replace(/&#8470;/g, "№")
      .replace(/\r{3,}/gm, "\r\r")
      .trim();
}
